In [3]:
import numpy as np

In [7]:
data = np.load('TicTacToeData.npy',allow_pickle=True)
print(data)
print(np.shape(data))

[array([[1, 2, 2, 2, 2, 2, 2, 2, 2],
       [1, 2, 2, 2, 2, 0, 2, 2, 2],
       [1, 2, 2, 2, 1, 0, 2, 2, 2],
       [1, 0, 2, 2, 1, 0, 2, 2, 2],
       [1, 0, 2, 1, 1, 0, 2, 2, 2],
       [1, 0, 2, 1, 1, 0, 2, 0, 2],
       [1, 0, 2, 1, 1, 0, 2, 0, 1]])
 array([[1, 2, 2, 2, 2, 2, 2, 2, 2],
       [1, 2, 2, 0, 2, 2, 2, 2, 2],
       [1, 2, 2, 0, 2, 2, 1, 2, 2],
       [1, 0, 2, 0, 2, 2, 1, 2, 2],
       [1, 0, 2, 0, 2, 1, 1, 2, 2],
       [1, 0, 2, 0, 2, 1, 1, 2, 0],
       [1, 0, 2, 0, 2, 1, 1, 1, 0],
       [1, 0, 0, 0, 2, 1, 1, 1, 0],
       [1, 0, 0, 0, 1, 1, 1, 1, 0]])
 array([[2, 0, 2, 2, 2, 2, 2, 2, 2],
       [2, 0, 2, 2, 2, 2, 2, 1, 2],
       [2, 0, 2, 2, 2, 0, 2, 1, 2],
       [2, 0, 1, 2, 2, 0, 2, 1, 2],
       [2, 0, 1, 2, 2, 0, 0, 1, 2],
       [2, 0, 1, 2, 2, 0, 0, 1, 1],
       [2, 0, 1, 2, 0, 0, 0, 1, 1],
       [1, 0, 1, 2, 0, 0, 0, 1, 1],
       [1, 0, 1, 0, 0, 0, 0, 1, 1]])
 ...
 array([[2, 0, 2, 2, 2, 2, 2, 2, 2],
       [2, 0, 2, 2, 1, 2, 2, 2, 2],
       [2, 0, 2,