In [124]:
import numpy as np

In [125]:
data = np.load("TicTacToeData.npy",allow_pickle=True)
data

array([array([[1, 2, 2, 2, 2, 2, 2, 2, 2],
       [1, 2, 2, 2, 2, 0, 2, 2, 2],
       [1, 2, 2, 2, 1, 0, 2, 2, 2],
       [1, 0, 2, 2, 1, 0, 2, 2, 2],
       [1, 0, 2, 1, 1, 0, 2, 2, 2],
       [1, 0, 2, 1, 1, 0, 2, 0, 2],
       [1, 0, 2, 1, 1, 0, 2, 0, 1]]),
       array([[1, 2, 2, 2, 2, 2, 2, 2, 2],
       [1, 2, 2, 0, 2, 2, 2, 2, 2],
       [1, 2, 2, 0, 2, 2, 1, 2, 2],
       [1, 0, 2, 0, 2, 2, 1, 2, 2],
       [1, 0, 2, 0, 2, 1, 1, 2, 2],
       [1, 0, 2, 0, 2, 1, 1, 2, 0],
       [1, 0, 2, 0, 2, 1, 1, 1, 0],
       [1, 0, 0, 0, 2, 1, 1, 1, 0],
       [1, 0, 0, 0, 1, 1, 1, 1, 0]]),
       array([[2, 0, 2, 2, 2, 2, 2, 2, 2],
       [2, 0, 2, 2, 2, 2, 2, 1, 2],
       [2, 0, 2, 2, 2, 0, 2, 1, 2],
       [2, 0, 1, 2, 2, 0, 2, 1, 2],
       [2, 0, 1, 2, 2, 0, 0, 1, 2],
       [2, 0, 1, 2, 2, 0, 0, 1, 1],
       [2, 0, 1, 2, 0, 0, 0, 1, 1],
       [1, 0, 1, 2, 0, 0, 0, 1, 1],
       [1, 0, 1, 0, 0, 0, 0, 1, 1]]),
       ...,
       array([[2, 0, 2, 2, 2, 2, 2, 2, 2],
       [2, 0, 2, 2

Crete new data frame that only has the final board for each game.

In [126]:
finalBoards = []

for i in range(len(data)):
    finalBoards.append(data[i][len(data[i])-1])


In [127]:
def match(state):
    spaceTaken = []
    for (pos,val) in enumerate(state):
        if val == 1 or val == 0: 
            spaceTaken.append(pos)

    my_list = []
    boardMatch = []

    for (pos,val) in enumerate(finalBoards):
        for i in spaceTaken:
            if state[i] == val[i]:
                my_list.append(True)
            else:
                my_list.append(False)
        if False not in my_list:
            boardMatch.append(val)
            my_list = []
        my_list = [] 
    newBoardMatch = []
    for i in boardMatch: 
        newBoardMatch.append(i.tolist())

    boardMatch = newBoardMatch

    newBoardMatch = []
    for i in boardMatch:
        if i not in newBoardMatch:
            newBoardMatch.append(i)
    
    boardMatch = newBoardMatch
    return boardMatch
    
print([1, 0, 2, 0, 2, 2, 1, 2, 2])
print(match([1, 0, 2, 0, 2, 2, 1, 2, 2]))
print(len(match([1, 0, 2, 0, 2, 2, 1, 2, 2])))
print(type(match([1, 0, 2, 0, 2, 2, 1, 2, 2])[3]))



[1, 0, 2, 0, 2, 2, 1, 2, 2]
[[1, 0, 0, 0, 1, 1, 1, 1, 0], [1, 0, 0, 0, 0, 1, 1, 1, 0], [1, 0, 1, 0, 0, 0, 1, 1, 0], [1, 0, 0, 0, 1, 1, 1, 0, 1], [1, 0, 0, 0, 0, 1, 1, 1, 1], [1, 0, 1, 0, 1, 1, 1, 0, 0], [1, 0, 1, 0, 0, 1, 1, 1, 0], [1, 0, 1, 0, 0, 1, 1, 0, 0], [1, 0, 1, 0, 1, 2, 1, 0, 2], [1, 0, 2, 0, 1, 0, 1, 0, 1], [1, 0, 2, 0, 0, 2, 1, 0, 1], [1, 0, 0, 0, 0, 1, 1, 0, 1], [1, 0, 0, 0, 1, 1, 1, 0, 0], [1, 0, 1, 0, 1, 2, 1, 2, 0], [1, 0, 2, 0, 0, 0, 1, 2, 1], [1, 0, 1, 0, 0, 0, 1, 2, 1], [1, 0, 0, 0, 0, 2, 1, 1, 1], [1, 0, 0, 0, 1, 0, 1, 1, 0], [1, 0, 2, 0, 0, 1, 1, 0, 1], [1, 0, 0, 0, 2, 0, 1, 1, 1], [1, 0, 1, 0, 1, 0, 1, 0, 1], [1, 0, 1, 0, 1, 0, 1, 1, 0], [1, 0, 2, 0, 2, 0, 1, 1, 1], [1, 0, 1, 0, 0, 1, 1, 0, 2], [1, 0, 1, 0, 0, 0, 1, 2, 2], [1, 0, 0, 0, 1, 2, 1, 0, 1], [1, 0, 2, 0, 0, 2, 1, 1, 1], [1, 0, 1, 0, 0, 0, 1, 0, 1], [1, 0, 1, 0, 1, 0, 1, 2, 0], [1, 0, 1, 0, 0, 0, 1, 1, 2], [1, 0, 0, 0, 1, 0, 1, 1, 1], [1, 0, 1, 0, 0, 2, 1, 0, 2], [1, 0, 2, 0, 0, 1, 1, 0, 2], [1, 0, 1, 0, 1